version: "3"
services:
  waf:
    image: openresty/openresty:alpine
    restart: always
    ports:
    - "80:80"
    volumes: 
    - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    - "./proxy.conf:/etc/nginx/conf.d/default.conf"
    - "./waf-scripts:/srv/waf-scripts"
    - "./data/logs:/logs"
    environment:
      COUNT_CYCLE: 10
      BASE_BAN_LIMIT: 20
      BASE_BAN_EXPIRE: 10
      SUPER_BAN_LIMIT: 50
      SUPER_EXPIRE: 3600
      REDISHOST: "192.168.88.66"
   # redis
#  redis:
#   image: redis:3.2-alpine
#   restart: always
#   ports:
#     - "6379:6379"
#   volumes:
#   - "./data/redis:/data"
  backend:
    image: registry.cn-shenzhen.aliyuncs.com/sync-dockerimage/nginx:1.17.1-alpine
    restart: always
