version: "3"
services: 
  waf:
    image: openresty/openresty:alpine
    ports: 
    - "80:80"
    volumes: 
    - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    - "./proxy.conf:/etc/nginx/conf.d/default.conf"
    - "./waf-scripts:/srv/waf-scripts"
    - "./logs:/logs"
    environment: 
      BLOCK_EXPIRE: 5 # second
      BLOCK_LIMIT: 10 # second