version: "3"
services:
  waf:
    image: openresty/openresty:alpine
    ports:
    - "80:80"
    volumes: 
    - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    - "./waf-scripts:/srv/waf-scripts"
    - "./conf.d:/etc/nginx/conf.d/"
    - "./logs:/logs"
    environment:
      BASE_COUNT_TTL: 10
      BASE_BAN_LIMIT: 10
      BASE_BAN_TTL: 60
      SUPER_BAN_LIMIT: 50
      SUPER_BAN_TLL: 3600
      REDISHOST: "192.168.88.66"
      REDISPORT: 6379
#  redis:
#   image: redis:3.2-alpine
#   ports:
#     - "6379:6379"
#   volumes:
#   - "./data/redis:/data"
  backend:
    image: registry.cn-shenzhen.aliyuncs.com/sync-dockerimage/nginx:1.17.1-alpine