version: "3"
services:
  waf:
    image: openresty/openresty:alpine
    ports:
    - "80:80"
    volumes: 
    - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    - "./proxy.conf:/etc/nginx/conf.d/default.conf"
    - "./waf-scripts:/srv/waf-scripts"
    - "./data/logs:/logs"
    environment:
      COUNT_CYCLE: 10
      BASE_BAN_LIMIT: 20
      BASE_BAN_EXPIRE: 10
      SUPER_BAN_LIMIT: 50
      SUPER_EXPIRE: 3600
      REDISHOST: "127.0.0.1"
  # # redis
  # redis:
  #   image: redis:3.2-alpine
  #   volumes:
  #   - "./data/redis:/data"